#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

COAUTHORS=~/.git-coauthors
TEMPLATE=~/.gitmessage

list () {
    cat "${COAUTHORS}" | jq -r '.coauthors | to_entries | .[] | "\(.key): \(.value.name) <\(.value.email)>"'
}

get_co_authors () {
    cat "${COAUTHORS}" | jq -r '.coauthors | to_entries | .[] | "Co-authored-by: \(.value.name) <\(.value.email)>"'
}

create_template () {
    touch "${TEMPLATE}"
    cat <<EOF > ${TEMPLATE}


$(get_co_authors)
EOF
}

enable () {
    create_template
    git config --local commit.template "${TEMPLATE}"
}

solo () {
    git config --local --unset commit.template
}
